### PR TITLE
Layout footer

### PR DESCRIPTION
**Pull request by rodrigo-morais**
Creating a footer to the blog.

### CODE REVIEW

**Comment by rodrigo-morais** [comment]
ping @viniciusffj

**Review by viniciusffj — COMMENTED** [review]
`footerView` has no message, it is all about markup. Why we need to Update and Message for that? I don't get it

**Comment by rodrigo-morais** [comment]
@viniciusffj Good call!
Removed!

**Comment by viniciusffj** [comment]
It looks good to me, merging

**Pull request merged**
